name: netresearch/rte-ckeditor-image
label: 'CKEditor Image Support'
# Optional dependencies: ensures our TypoScript loads AFTER these packages
# if they're present, but doesn't require them if users have custom rendering
optionalDependencies:
  - typo3/fluid-styled-content
  - bk2k/bootstrap-package
