services:
    web:
        environment:
            - EXTENSION_KEY=rte_ckeditor_image
            - PACKAGE_NAME=netresearch/rte-ckeditor-image

            # TYPO3 v13 config
            - TYPO3_DB_DRIVER=mysqli
            - TYPO3_DB_USERNAME=root
            - TYPO3_DB_PASSWORD=root
            - TYPO3_DB_HOST=db
            - TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
            - TYPO3_SETUP_ADMIN_USERNAME=admin
            - TYPO3_SETUP_ADMIN_PASSWORD=Joh316!!
            - TYPO3_PROJECT_NAME=EXT:rte_ckeditor_image Dev Environment
            - TYPO3_SERVER_TYPE=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/rte_ckeditor_image
              consistency: cached
            - v13-data:/var/www/html/v13
volumes:
    v13-data:
        name: "${DDEV_SITENAME}-v13-data"
